version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile-dev
      context: .
    command: npm run dev
    ports:
      - "3000:3000/tcp"
      - "9229:9229/tcp"
    volumes:
      - "./:/home/node/app"
