version: '3'

services:
  db:
    image: mysql:5
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_ROOT_HOST
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - ./mysqldata:/var/lib/mysql
  app:
    build:
      dockerfile: Dockerfile-dev
      context: .
    command: npm run dev
    volumes:
      - "./:/home/node/app/"
    environment:
      - EXAMPLE=db
    ports:
      - "3000:3000/tcp"
    depends_on:
      - db
  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080
    depends_on:
      - db
